### ISSUE TITLE
Extract toast feature into separate framework

### ISSUE THREAD

**Issue by pbodsk** [nodes-ios/Reachability-UI#15]
We need a new framework to handle toast messages. Bits and pieces of that feature already exists here so let us extract that into a new framework.

## Ideas
- The new framework must be able to expose itself as a `MessageDisplayer` (feel free to come up with a better name) which can be used from other frameworks (Reachability-UI for instance) to display messages delivered to it. So you register a `MessageDisplayer` in your project and can then use that to deliver output on screen.

## Naming Candidates
- Toastmaster
- Toaster
- Rye

**Comment by kjoneandrei** [comment]
done in https://github.com/nodes-ios/Rye
